#!/usr/bin/env python3

from configparser import ConfigParser
from argparse import ArgumentParser


if __name__ == '__main__':
  arg_parser = ArgumentParser()
  arg_parser.add_argument('--file', required=True)
  arg_parser.add_argument('--key', required=True)
  arg_parser.add_argument('--value', required=True)
  args = arg_parser.parse_args()

  cfg = ConfigParser()
  with open(args.file, 'r') as f:
    cfg.read_file(args.file)

  cfg.set(None, args.key, args.value)

  with open(args.file, 'w') as f:
    cfg.write(f)
