#!/usr/bin/env python3

from configparser import ConfigParser
from argparse import ArgumentParser
from os.path import isfile


if __name__ == '__main__':
  arg_parser = ArgumentParser()
  arg_parser.add_argument('--file', required=True)
  arg_parser.add_argument('--key', required=True)
  arg_parser.add_argument('--value', required=True)
  args = arg_parser.parse_args()

  cfg = ConfigParser()
  if isfile(args.file):
    with open(args.file, 'r') as f:
      cfg.read_file(f)

  cfg.set(None, args.key, args.value)

  with open(args.file, 'w') as f:
    cfg.write(f)
