name: fr24feed
version: '0.0.2'
summary: Flightradar24 feed
description: |
    Flightradar24 Decoder & Feeder lets you effortlessly share ADS-B data with
    Flightradar24. It supports multiple receivers, includes all dependencies
    the DVBT stick and makes the entire feeding process as smooth as possible.
    Package includes librtlsdr (released under GPLv2) and dump1090 (released
    under BSD) binaries. Source code can be downloaded from
    http://feed.flightradar24.com/raspberry-pi.

grade: devel
confinement: strict
architectures: [ armhf ]

apps:
  fr24feed:
    command: 'fr24feed --config-file="${SNAP_USER_COMMON}/fr24feed.ini" --logpath="${SNAP_USER_COMMON}"'
    daemon: simple
    plugs:
     - network
     - network-observe # required for ping

parts:
  fr24feed:
    plugin: dump
    source: http://repo.feed.flightradar24.com/rpi_binaries/fr24feed_1.0.18-7_armhf.tgz
    #source-checksum: sha3_384/c2610b3697fce23515b557b9e6a52c85ea9d48b5bbaf55b7af37fffffa19074b4a0f4fa352f90ce25b17921615070fd5
    source-type: tar
    organize:
      fr24feed: bin/fr24feed
    filesets:
      binaries: [ bin/* ]
      licences: [ LICENSE* ]
    stage:
     - $binaries
     - $licences
    stage-packages:
     - zlib1g
  fr24config:
    plugin: dump
    source: .
    organize:
      fr24config: bin/fr24config
    filesets:
      binaries: [ bin/* ]
    stage:
     - $binaries
