name: fr24feed
version: '0.0.1'
summary: Flightradar24 feed
description: |
    Flightradar24 Decoder & Feeder lets you effortlessly share ADS-B data with
    Flightradar24. It supports multiple receivers, includes all dependencies
    the DVBT stick and makes the entire feeding process as smooth as possible.
    Package includes librtlsdr (released under GPLv2) and dump1090 (released
    under BSD) binaries. Source code can be downloaded from
    http://feed.flightradar24.com/raspberry-pi.

grade: devel
confinement: strict
architectures: [armhf]

apps:
  fr24feed:
    command: 'bin/fr24feed --config-file="${SNAP_USER_COMMON}/fr24feed.ini"'
    daemon: simple
    plugs:
     - network

parts:
  fr24feed:
    plugin: dump
    source: http://repo.feed.flightradar24.com/rpi_binaries/fr24feed_1.0.18-7_armhf.tgz
    source-type: tar
    organize:
      fr24feed: bin/fr24feed
    filesets:
      binaries: [ bin/* ]
      licences: [ LICENSE* ]
    stage:
     - $binaries
     - $licences

