name: fr24feed
version: '0.0.2'
summary: Flightradar24 feed
description: |
    Flightradar24 Decoder & Feeder lets you effortlessly share ADS-B data with
    Flightradar24. It supports multiple receivers, includes all dependencies
    the DVBT stick and makes the entire feeding process as smooth as possible.
    Package includes librtlsdr (released under GPLv2) and dump1090 (released
    under BSD) binaries. Source code can be downloaded from
    http://feed.flightradar24.com/raspberry-pi.

grade: devel
confinement: strict
architectures: [ armhf ]

apps:
  fr24feed:
    command: 'fr24feed --config-file="${SNAP_USER_COMMON}/fr24feed.ini" --logpath="${SNAP_USER_COMMON}" --monitor-file="/dev/shm/snap.${SNAP_NAME}.decoder.txt" --raw=no --bs=no --mpx=no'
    daemon: simple
    plugs:
     - network
     - network-bind
     - network-observe # required for ping (but doesn't work)
     - network-control # Fix?? for ping
     - firewall-control # Fix?? for ping
     - time-control # NTP

parts:
  fr24feed:
    plugin: dump
    source: http://repo.feed.flightradar24.com/rpi_binaries/fr24feed_1.0.18-9_armhf.tgz
    #source-checksum: sha3_384/31b529ea4b67c1c61a0d42eb9b887ca4c6a2419fb00759c1511910414a06c167e0f061a50eff9c611946424507cff4aa
    source-type: tar
    organize:
      fr24feed: bin/fr24feed
    filesets:
      binaries: [ bin/* ]
      licences: [ LICENSE* ]
    stage:
     - $binaries
     - $licences
    stage-packages:
     - zlib1g
     - iputils-ping
  fr24config:
    plugin: dump
    source: .
    organize:
      fr24config: bin/fr24config
    filesets:
      binaries: [ bin/* ]
    stage:
     - $binaries
