name: fr24feed
version: '0.0.2'
summary: Flightradar24 feed
description: |
    Flightradar24 Decoder & Feeder lets you effortlessly share ADS-B data with
    Flightradar24. It supports multiple receivers, includes all dependencies
    the DVBT stick and makes the entire feeding process as smooth as possible.
    Package includes librtlsdr (released under GPLv2) and dump1090 (released
    under BSD) binaries. Source code can be downloaded from
    http://feed.flightradar24.com/raspberry-pi.

grade: devel
confinement: strict
architectures: [ armhf ]

apps:
  fr24feed:
    command: 'fr24feed --config-file="${SNAP_USER_COMMON}/fr24feed.ini"'
    daemon: simple
    plugs:
     - network
     - network-observe # required for ping
     - raw-usb

parts:
  fr24feed:
    plugin: dump
    source: http://repo.feed.flightradar24.com/rpi_binaries/fr24feed_1.0.18-9_armhf.deb
    source-type: deb
    stage-packages:
     - zlib1g
     - libusb-1.0-0
  fr24config:
    plugin: dump
    source: .
    organize:
      fr24config: bin/fr24config
    filesets:
      binaries: [ bin/* ]
    stage:
     - $binaries
