
name: fr24feed
version: '0.0.1'
summary: Flightradar24 feed
description: |
  Flightradar24 operates the world's largest network of ADS-B/Mode S receivers.
  This network, together with government air traffic control and other data
  sources, is how Flightradar24 is able to track aircraft around the globe.

grade: devel
confinement: strict
architectures: [armhf]

apps:
  fr24feed:
    command: fr24feed
    daemon: simple
    plugs:
     - network

parts:
  fr24feed:
    plugin: dump
    source: http://repo.feed.flightradar24.com/rpi_binaries/fr24feed_1.0.18-7_armhf.tgz
    source-type: tar
